name: CI Base

# Eventi che attivano il workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Permessi di default per il workflow
permissions:
  contents: read
  pull-requests: write

jobs:
  # Job di base che esegue alcuni controlli
  basic-checks:
    name: Basic Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Check repository structure
        run: |
          echo "Verifico la struttura del repository..."
          ls -la
          echo "Verifico la presenza delle directory principali..."
          [ -d "src" ] && echo "✓ Directory src presente" || echo "✗ Directory src mancante"
          [ -d "tests" ] && echo "✓ Directory tests presente" || echo "✗ Directory tests mancante"
          [ -d ".github/workflows" ] && echo "✓ Directory .github/workflows presente" || echo "✗ Directory .github/workflows mancante"

      - name: Create test file
        run: |
          echo "Creo un file di test nella directory tests..."
          echo "# Test file" > tests/test.txt
          echo "Questo è un file di test" >> tests/test.txt

      - name: List test directory
        run: |
          echo "Contenuto della directory tests:"
          ls -la tests/

      - name: Add comment to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Basic checks completed successfully!'
            })

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pytest tests/ -v --cov=src

      - name: Check repository structure
        run: |
          echo "Verifico la struttura del repository..."
          ls -la
          echo "Verifico la presenza delle directory principali..."
          [ -d "src" ] && echo "✓ Directory src presente" || echo "✗ Directory src mancante"
          [ -d "tests" ] && echo "✓ Directory tests presente" || echo "✗ Directory tests mancante"
          [ -d ".github/workflows" ] && echo "✓ Directory .github/workflows presente" || echo "✗ Directory .github/workflows mancante"

      - name: Add comment to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Tests completed successfully!'
            }) 